// <auto-generated />
namespace Sensei.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SensorMeasurement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SensorMeasurement));
        
        string IMigrationMetadata.Id
        {
            get { return "201711091623405_Sensor-Measurement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
